### ISSUE TITLE
Does not build in Angular workspaces

### ISSUE THREAD

**Issue by kneeki** [cherryApp/ngc-esbuild#4]
I'm given the following error when executing `ngc-esbuild`:
```
✘ [ERROR] [plugin angularAssetsResolver] ENOENT: no such file or directory, scandir '/home/dave/work/esbuild-workspace-test/src/assets'

(node:27860) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
error: ENOENT: no such file or directory, scandir '/home/dave/work/esbuild-workspace-test/src/assets'
    at failureErrorWithLog (/home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:1557:15)
    at /home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:1102:18    at /home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:1097:9 
    at /home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:637:9  
    at handleIncomingPacket (/home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:734:9)
    at Socket.readFromStdout (/home/dave/.nvm/versions/node/v14.18.2/lib/node_modules/ngc-esbuild/node_modules/esbuild/lib/main.js:604:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Steps to recreate
```bash
ng new esbuild-workspace-test --no-create-application
cd esbuild-workspace-test/
ng g application test --routing --style scss
ngc-esbuild
```

**Comment by nickbanana** [comment]
may I ask about which version of the @angular/cli you are using?

**Comment by kneeki** [comment]
Apologies I forgot to include that!

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.2.15
Node: 14.18.2
Package Manager: npm 6.14.15
OS: linux x64

Angular: 12.2.15
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.15
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            12.2.15
@angular-devkit/schematics      12.2.15
@schematics/angular             12.2.15
ng-packagr                      12.2.6
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.66.0
```

**Comment by nickbanana** [comment]
seems like in recent version of angular cli, it will generate a folder called "project" to host all application created via cli

Current version of ngc-esbuild haven't support that. Might add some implementation to let it work

**Comment by cherryApp** [comment]
Hi guys!
ver 0.0.61 supports the workspaces with this syntax in the package.json:
```json
"start":  "ngc-esbuild --project app2" 
```
app2 is the name of the current project from angular.json
