### ISSUE TITLE
add support of lazy loading css and js in angular.json

### ISSUE THREAD

**Issue by nickbanana** [cherryApp/ngc-esbuild#5]
while I use npx ngc-esbuild with some relatively small project, which node version is on 12.18.3, multiple error related to angularVendorJSResolver and angularCSSProcessor

```
X [ERROR] [plugin angularCSSProcessor] item.includes is not a function

    C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:87:32:
      87 │           const itemPath = item.includes('/')
         ╵                                 ^

    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:87:33
    at Array.forEach (<anonymous>)
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:86:24
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1011:21
    at runOnEndCallbacks (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1016:11)
    at buildResponseToResult (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1213:7)
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1322:14
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:637:9
    at handleIncomingPacket (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:734:9)
    at Socket.readFromStdout (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:604:7)

  This error came from the "onEnd" callback registered here:

    C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:76:12:
(node:16684) UnhandledPromiseRejectionWarning: Error: EBUSY: resource busy or locked, copyfile 'D:\work\tttc\frontend\client-second\node_modules\bootstrap\dist\fonts\glyphicons-halflings-regular.eot' -> 'D:\work\tttc\frontend\client-second\dist\esbuild\glyphicons-halflings-regular.eot'
(node:16684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 47)
(node:16684) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'D:\work\tttc\frontend\client-second\node_modules\bootstrap\dist\fonts\glyphicons-halflings-regular.svg#glyphicons_halflingsregular' -> 'D:\work\tttc\frontend\client-second\dist\esbuild\glyphicons-halflings-regular.svg#glyphicons_halflingsregular'
(node:16684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 48)
      76 │       build.onEnd(async () => {
         ╵             ~~~~~

    at setup (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:76:13) 
    at handlePlugins (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:814:23)
```

```
X [ERROR] [plugin angularVendorJSResolver] item.includes is not a function

    C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:22:32:
      22 │           const itemPath = item.includes('/')
         ╵                                 ^

    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:22:33
    at Array.forEach (<anonymous>)
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:21:24
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1011:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

  This error came from the "onEnd" callback registered here:

    C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:10:12:
      10 │       build.onEnd(async () => {
         ╵             ~~~~~

    at setup (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:10:13)  
    at handlePlugins (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:814:23)
```

```
(node:16684) UnhandledPromiseRejectionWarning: Error: Build failed with 2 errors:
C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:87:32: ERROR: [plugin: angularCSSProcessor] item.includes is not a function
C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\bin\plugin\esbuild-js-resolver.js:22:32: ERROR: [plugin: angularVendorJSResolver] item.includes is not a function
    at failureErrorWithLog (C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1557:15)
    at C:\Users\nickc\AppData\Roaming\npm-cache\_npx\16684\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:1215:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:16684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 50)
```

**Comment by nickbanana** [comment]
after a bit triage, current version of ngc-esbuild (0.0.56) might can't support dynamic inject of js/css in the format of

`{"input": "some-path-to-certain-css-or-scss.css", "inject": false},`

`{"input": "some-path-to-certain-built-js.js", "inject": false, "bundleName": "some-bundle-name"},`

**Comment by cherryApp** [comment]
Thanks for your feedback.
I found a reasonable explanation about this technic:
https://juristr.com/blog/2019/08/dynamically-load-css-angular-cli/

It is currently not an issue, instead of a feature request.
Our builder reads the angular.json when it starts.
https://github.com/cherryApp/ngc-esbuild/blob/b6f7d00cc0496b787a18418c9c84a7f0e7fdfead/bin/plugin/esbuild-settings-resolver.js#L14

I think if we find those options, we can implement this feature.

**Comment by nickbanana** [comment]
> I think if we find those options, we can implement this feature.
Ok, I would like to contribute the development (not on this feature request but general development), do you have guideline about how to contribute the code? (like coding style/commit message format etc.)

**Comment by cherryApp** [comment]
Thank you so mutch.
The guide is here: https://github.com/cherryApp/ngc-esbuild/blob/main/CONTRIBUTING.md#reporting-bugs

If you're sure, I'll hire you as a collaborator.

**Comment by nickbanana** [comment]
> Thank you so mutch. The guide is here: https://github.com/cherryApp/ngc-esbuild/blob/main/CONTRIBUTING.md#reporting-bugs
> 
> If you're sure, I'll hire you as a collaborator.

First, just let you know I'm a full-time frontend developer, so weekend and work off time is only moment for me to contribute.

Second, this is my first time developing build tool, so it's also a learning experience for me.

If you're fine with these circumstances, then I'll glad to collaborate with you 👍 

lastly, to prevent the least conflict on code, which version of node you're developing on? also which range of Angular version you would like to support?

**Comment by nickbanana** [comment]
> If you are in, please check the mentioned code, and send me a pull-request.

First, does mentioned code is the CONTRIBUTING.md? (I've done the reading)

Second, about send you a pull-request, is it mean that I fork the project, make an empty commit, push and send a PR to you? Or just heads on solving opening issue like #4 ?

Lastly, is there any other contact method other than commenting here (i.e. Email)? I think this thread is becoming off-topic

Sorry for having so many questions, but I would love to contribute this project

**Comment by cherryApp** [comment]
Hi @nickbanana,
Did you check the solution?
The new 0.0.63 version contains a patch for this problem.

**Comment by nickbanana** [comment]
``` sh
X [ERROR] [plugin angularCSSProcessor] item.includes is not a function

    C:\Users\nickc\AppData\Roaming\npm\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:19:30:
      19 │         const itemPath = item.includes('/')
         ╵                               ^

    at C:\Users\nickc\AppData\Roaming\npm\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:19:31
    at Array.forEach (<anonymous>)
    at setup (C:\Users\nickc\AppData\Roaming\npm\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:18:30)
    at async handlePlugins (C:\Users\nickc\AppData\Roaming\npm\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:856:11)

(node:1348) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
C:\Users\nickc\AppData\Roaming\npm\node_modules\ngc-esbuild\bin\plugin\esbuild-css-resolver.js:19:30: ERROR: [plugin: angularCSSProcessor] item.includes is not a function
```

Seems like the problem persist, though remove the objects in the style array still trigger the error, I might check the error off work.

**Comment by cherryApp** [comment]
I modified the CSS resolver.
Please check version 0.0.64.
I didn't implement this functionality for JS yet.

**Comment by nickbanana** [comment]
> I modified the CSS resolver. Please check version 0.0.64. I didn't implement this functionality for JS yet.

Looks good to me, the lazy-loading part is good but 
```js
const externalModuleConfig = { input: '', inject: false, bundleName: '' };
```
the default bundleName is empty and it'll make the output filename is 'undefined.css'

**Comment by cherryApp** [comment]
I see.
When bundleName is not provided, NGC uses the original filename.
Check the version 0.0.65.

**Comment by nickbanana** [comment]
> I see. When bundleName is not provided, NGC uses the original filename. Check the version 0.0.65.

looks good to me

**Comment by cherryApp** [comment]
Thanks.
I will make the .js version of it too.
I appreciate your help.

**Comment by cherryApp** [comment]
Good news!

Version 0.0.68 now supports the lazy-loading CSS and JS files.
